import Head from 'next/head'
import NextLink from 'next/link'
import { useState, useEffect, ChangeEvent } from 'react'
import { useRouter } from 'next/router'
import { v4 as uuidv4 } from 'uuid'
import supabase from '@/lib/supabase'
import {
  useSDK,
  Web3Button,
  useAddress,
  useContract,
  useContractRead,
  useContractWrite,
  useContractEvents,
} from '@thirdweb-dev/react'
import { CONTRACT_ADDRESSES } from '@/contracts/constants'
import GroupFactoryAbi from '@/contracts/GroupFactoryAbi.json'
import { Stack, Button, Text, Input, Link } from '@chakra-ui/react'

export default function Home() {
  const router = useRouter()

  const address = useAddress()
  const { contract } = useContract(
    CONTRACT_ADDRESSES.GroupFactory,
    GroupFactoryAbi,
  )

  const [groupImage, setGroupImage] = useState<File | null>(null)
  const [groupName, setGroupName] = useState('')

  const handleChangeImage = (event: ChangeEvent<HTMLInputElement>) => {
    if (event.target.files && event.target.files[0]) {
      setGroupImage(event.target.files[0])
    }
  }

  const handleChange = (event: ChangeEvent<HTMLInputElement>) => {
    setGroupName(event.target.value)
  }

  const {
    mutateAsync: mutateCreateGroup,
    isLoading,
    error,
  } = useContractWrite(contract, 'createGroup')

  const createGroup = async () => {
    try {
      const groupId = uuidv4()

      const imageFilePath = `images/groups/${groupId}/membership.png`
      const { data, error: imageUploadError } = await supabase.storage
        .from('metadata')
        .upload(imageFilePath, groupImage!)

      if (imageUploadError) {
        console.error('Error uploading image:', imageUploadError)
        return
      }

      const {
        data: { publicUrl: imagePublicUrl },
      } = await supabase.storage.from('metadata').getPublicUrl(imageFilePath)
      console.log('imagePublicUrl', imagePublicUrl)

      const groupData = {
        name: `${groupName} membership NFT`,
        description: `about ${groupName} membership`,
        image: imagePublicUrl,
        attributes: [
          {
            trait_type: 'メンバータイプ',
            value: '運営メンバー',
          },
          {
            trait_type: '役割',
            value: 'エンジニア',
          },
        ],
      }

      const jsonFilePath = `json/groups/${groupId}/membership.json`
      const { error: jsonUploadError } = await supabase.storage
        .from('metadata')
        .upload(
          jsonFilePath,
          new Blob([JSON.stringify(groupData)], { type: 'application/json' }),
          { contentType: 'application/json' },
        )

      if (jsonUploadError) {
        console.error('Error uploading JSON:', jsonUploadError)
        return
      }

      const {
        data: { publicUrl: jsonPublicUrl },
      } = supabase.storage.from('metadata').getPublicUrl(jsonFilePath)

      console.log('jsonPublicUrl', jsonPublicUrl)

      const { receipt } = await mutateCreateGroup({
        args: [groupId, jsonPublicUrl],
      })
      const groupAddress = (receipt as any).events[0].address

      const { error } = await supabase.from('groups').insert({
        id: groupId,
        name: groupName,
        contract_address: groupAddress,
        creator_address: address,
      })

      if (error) {
        console.error('Error inserting data:', error)
      }

      const { error: error2 } = await supabase
        .from('group_member')
        .insert({ group_id: groupId, member_address: address })

      if (error2) {
        console.error('Error inserting data:', error2)
      }

      router.push(`/groups/${groupId}`)
    } catch (e) {
      console.log('e', e)
    }
  }

  return (
    <>
      <Head>
        <title>thirdevent</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Stack>
        {address && (
          <>
            <Input
              placeholder='Enter Group Name'
              value={groupName}
              onChange={handleChange}
            />
            <Input type='file' accept='image/*' onChange={handleChangeImage} />
            <Button onClick={createGroup} isLoading={isLoading}>
              Create Group
            </Button>

            <Text>GroupFactory Address: {CONTRACT_ADDRESSES.GroupFactory}</Text>
          </>
        )}
      </Stack>
    </>
  )
}
