import { GetServerSideProps } from 'next'
import Head from 'next/head'
import supabase from '@/lib/supabase'
import { Event } from '@/types'
import {
  Stack,
  Box,
  Button,
  Text,
  Input,
  Link,
  Heading,
  Flex,
  Card,
  CardHeader,
  CardBody,
  CardFooter,
  Image,
} from '@chakra-ui/react'

interface HomeProps {
  events: Event[]
}

export const getServerSideProps: GetServerSideProps<HomeProps> = async () => {
  const { data } = await supabase
    .from('events')
    .select('*, group:groups(*)')
    .neq('thumbnail', null)
  console.log(data)

  const events =
    data?.map(
      (d) =>
        ({
          id: d.id,
          contractAddress: d.contract_address,
          title: d.title,
          thumbnail: d.thumbnail,
          group: {
            id: d.group.id,
            name: d.group.name,
            contractAddress: d.group.contract_address,
          },
        } as Event),
    ) ?? []

  // フェッチしたデータをプロップスとして返す
  return {
    props: {
      events,
    },
  }
}

const Home = ({ events }: HomeProps) => {
  return (
    <>
      <Head>
        <title>thirdevent</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Stack>
        <Heading size='md'>イベント一覧</Heading>

        <Flex gap={4} mt={6} flexWrap={'wrap'}>
          {events.map((event) => (
            <Link
              key={event.id}
              href={`events/${event.id}`}
              textDecoration='none !important'
            >
              <Card maxW='sm' width='200px' borderRadius='lg'>
                <CardBody p={0}>
                  <Image
                    src={event.thumbnail}
                    alt={event.title}
                    borderTopRadius='lg'
                    boxSize={'150px'}
                    width='100%'
                    objectFit='cover'
                  />
                  <Stack mt={2} spacing={3} p={2}>
                    <Text
                      fontSize='sm'
                      fontWeight='bold'
                      noOfLines={2}
                      height='40px'
                    >
                      {event.title}
                    </Text>

                    <Text color='teal.500' fontSize='2xl'>
                      5月1日
                    </Text>
                  </Stack>
                </CardBody>
              </Card>
            </Link>
          ))}
        </Flex>
      </Stack>
    </>
  )
}

export default Home
